version: '3.8'

services:
  db-prod:
    image: crud-database:3a1ff16
    container_name: crud-production-db
    restart: always
    environment:
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prod_secure_password_2026
      POSTGRES_DB: production_crud_db
    ports:
      - "5432:5432"
    volumes:
      - prod_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prod_user -d production_crud_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend-prod:
    image: crud-backend:3a1ff16
    container_name: crud-production-backend
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgres://prod_user:prod_secure_password_2026@db-prod:5432/production_crud_db
      JWT_SECRET: super_secret_production_key_9988
    ports:
      - "3001:3001"
    depends_on:
      db-prod:
        condition: service_healthy

  frontend-prod:
    image: crud-frontend:3a1ff16
    container_name: crud-production-frontend
    restart: always
    ports:
      - "9000:8080"

volumes:
  prod_db_data:
    driver: local
